spring.application.name=adnceiba
spring.datasource.url=jdbc:postgresql://localhost:5432/adnceiba
spring.datasource.username=postgres
spring.datasource.password=3043341677
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true